name: Fetch Postgres Dynamic Secrets
'on': push
jobs:
  fetch_postgres_dynamic_secrets:
    runs-on: self-hosted
    name: Fetch Postgres Dynamic Secrets
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          dynamic-secrets: |
            - name: "/postgres1-dyn"
              output-name: "postgres_dynamic_secret"
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          api-url: 'https://csm.thalescryptolabs.com/akeyless-api/v2/'
      # - name: Export Secrets to Environment
      #   run: |
      #    echo ${{ steps.fetch-dynamic-secrets.outputs.postgres_dynamic_secret }}
      - name: Verify Vars
        run: |
          echo "host: ${{ env.host }} " >> secrets.txt
          echo "port: ${{ env.port }} " >> secrets.txt
          echo "username: ${{ env.user }} " >> secrets.txt
          echo "password: ${{ env.password }} " >> secrets.txt
          echo "db_name: ${{ env.db_name }} " >> secrets.txt
          echo "ttl_in_minutes: ${{ env.ttl_in_minutes }} " >> secrets.txt           
